; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_deps = 
    h2zero/NimBLE-Arduino@^1.4.3
board_build.partitions = partitions.csv
monitor_speed = 115200
build_flags = 
    -DARDUINO_ARCH_ESP32
    -DESP_PLATFORM
    -DCONFIG_BT_NIMBLE_ENABLED=1
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
    -DCONFIG_BT_NIMBLE_MAX_BONDS=3
    -DCONFIG_BT_NIMBLE_MAX_CCCDS=8
    -DCONFIG_BT_NIMBLE_PINNED_TO_CORE=0
    -DCONFIG_BT_NIMBLE_TASK_STACK_SIZE=4096
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL
    -DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL
    -DCONFIG_BT_NIMBLE_ROLE_BROADCASTER
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER
    -DCONFIG_BT_NIMBLE_NVS_PERSIST
    -DCONFIG_BT_NIMBLE_SM_LEGACY
    -DCONFIG_BT_NIMBLE_SM_SC
    -DCONFIG_BT_NIMBLE_USE_ESP_TIMER
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_DFU_ON_BOOT=0
    -DCONFIG_ARDUHAL_LOG_COLORS=1
    -DCONFIG_ARDUHAL_ESP_LOG=1
build_unflags = 
    -DCONFIG_BT_ENABLED
    -DCONFIG_BTDM_CTRL_MODE_BLE_ONLY
    -DCONFIG_BTDM_CTRL_MODE_BR_EDR_ONLY
    -DCONFIG_BTDM_CTRL_MODE_BTDM
